---
title: "R Notebook"
output: html_notebook
---

```{r}

dataset <- read.csv("C:/Users//Desktop/data_for_class.csv",header=TRUE)

str(dataset)

dat <- dataset

miles <- dat$MILES
income <- dat$INCOME
age <- dat$AGE
kids <- dat$KIDS
```

```{r}
lse <- lm(miles~income+age+kids)
summary(lse)

y <- as.matrix(miles)
y
dim(y)

X <- cbind(1,income,age,kids)
X
dim(X)

b <- crossprod(solve(crossprod(X,X)),crossprod(X,y))
b
dim(b)

e <- y-X%*%b
e
summary(e)

n <- nrow(X)
i <- as.matrix(X[,1])
m0 <- diag(n)-i%*%solve(crossprod(i,i))%*%t(i)
```

```{r}
tss <- t(y)%*%m0%*%y
rss <- crossprod(e,e)
ess <- tss-rss

R2  <- ess/tss
R2

k <- ncol(X)
nmk <- n-k
nmk

adjR2 <- (1-k)/nmk+(n-1)/nmk*R2
adjR2

s2 <- as.numeric(rss/nmk)
s2

s <- s2^0.5
s

VCOV <- s2*solve(crossprod(X,X))
VCOV

var <- diag(VCOV)
var

se <- var^0.5
se

trat <- b/se
trat

pvt <- 2*pt(-abs(trat),df=nmk)
pvt

```

```{r}
results <- cbind(b,se,trat,pvt)
colnames(results) <- c("Estimate","Std. Error","t value","Pr(>|t|)")
rownames(results) <- c("intercept","income","age","kids")
round(results,digits=4)

q <- ncol(X)-1
q

null <- matrix(0:0,q)
ikm1 <- diag(q)
R <- cbind(null,ikm1)
R

r <- matrix(0:0,q)
r

Rbetamr <- R%*%b-r
Rbetamr

F <- t(Rbetamr)%*%solve(R%*% VCOV %*%t(R))%*%Rbetamr/q
F

pvF <- 1-pf(F,df1=q,df2=nmk)
pvF

vcov(lse)
coefficients(lse)
residuals(lse)
fitted.values(lse)
y-e



```

